from django.urls import path
from . import views
from .oauth import refetch_profile


urlpatterns = [
    path('', views.home.index, name='index'),
    path('accounts/profile/', refetch_profile, name='profile'),
    path('accounts/edit-profile/', views.profile.edit_profile, name='edit_profile'),
    path('accounts/signup/', views.auth.register, name='register'),
    path('accounts/login/', views.auth.login, name='login'),
    path('accounts/logout/', views.auth.logout, name='logout'),
    path('accounts/profile/<int:pk>/', views.auth.change_profile, name='change_profile'),
    path('check-auth/', views.auth.check_auth, name='check_auth'),
    path('dashboard/', views.listings.dashboard, name='dashboard'),
    path('accounts/change-password/', views.auth.change_password, name='change_password'),
    path('profile_overview/', views.auth.profile_overview, name='profile_overview'),
    path('category/', views.home.get_all_categories, name='all_categories'),
    path('category/<slug:slug>/', views.home.get_all_sub_categories, name='all_sub_categories'),
    path('category/<slug:category_slug>/<slug:sub_cat_slug>/', views.home.get_products, name='products'),
    path('product/<slug:slug>/', views.home.product_details, name='product_details'),
    path('search/', views.home.auto_complete_model, name='search'),
    path('industries/', views.home.get_all_industry, name='all_industry'),
    path('give-rating/', views.home.save_rating, name='save_rating'),
    path('edit-rating/', views.home.edit_rating, name='edit_rating'),
    path('get-inquiry-form/', views.home.get_product_inquiry_form, name='inquiry_form'),
    path('save-inquiry-data/', views.home.save_inquiry, name='save_inquiry'),
    path('industries/<slug:industry_slug>/', views.home.get_all_products_by_industry, name='all_products_by_industry'),
    path('dashboard/products/', views.listings.products_listing, name='products_listing'),
    path('dashboard/products/<int:pk>/', views.listings.product_detail, name='product_detail'),
    path('dashboard/products/create/', views.listings.create_product, name='create_product'),
    path('dashboard/products/edit/<int:pk>/', views.listings.edit_product, name='edit_product'),
    path('dashboard/products/delete/<int:pk>/', views.listings.delete_product, name='delete_product'),
    path('dashboard/get-price-structure/', views.listings.get_price_form, name='get_price_form'),
    path('dashboard/get-product-delivery-form/', views.listings.get_product_delivery_form,
         name='product_delivery_form'),
    path('ajax_calls/get-sub-categories/', views.listings.get_sub_categories_by_cat_id, name='ge_sub_cat'),
    path('ajax_calls/get-sub-categories-products/', views.listings.get_product_by_sub_cat, name='get_product_by_sub_cat'),
    path('ajax_calls/get-products-by-ids/', views.listings.get_product_by_ids, name='get_product_by_ids'),
    path('dashboard/get-product-delivery-details/', views.listings.get_delivery_detail_by_product_id,
         name='product_delivery_details'),
    path('dashboard/make-featured-img/<int:pk>/', views.listings.make_image_as_feature_img,
         name='make_image_as_feature_img'),
    path('dashboard/inquiries/', views.listings.inquiry_lists, name='inquiry_lists'),
    path('validate-promo-code/', views.listings.validate_promo_code, name='validate_promo_code'),
    path('get-max-price/', views.listings.get_max_price, name='max_price'),
    path('get-borrowers-lists/', views.listings.get_borrowers_lists, name='get_borrowers_lists'),
    path('get-borrower-details/', views.listings.get_borrower_details, name='get_borrower_details'),
    path('check-bill-no-exists/', views.listings.check_bill_no_exists, name='check_bill_no_exists'),
    path('dashboard/rewards/', views.listings.get_reward_point, name='get_reward_point'),
    path('dashboard/dealersgivenfinanceschememes/', views.listings.dealers_scheme_list, name='dealers_scheme_list'),
    path('dashboard/schemes/create/', views.listings.dealers_scheme_create, name='dealers_scheme_create'),
    path('dashboard/schemes/edit/<int:id>/', views.listings.dealers_scheme_edit, name='dealers_scheme_edit'),
    path('dashboard/schemes/delete/<int:id>/', views.listings.dealers_scheme_delete, name='dealers_scheme_delete'),
    path('check-scheme-exists/', views.listings.check_scheme_exists, name='check_scheme_exists'),

    # Content pages
    path('veloce/content/about_veloce_market/', views.listings.about_veloce_market, name='about_veloce_market'),
    path('veloce/content/how_veloce_market_work/', views.listings.how_veloce_market_work, name='how_veloce_market_work'),
    path('veloce/content/faqs_ftr/', views.listings.faqs_ftr, name='faqs_ftr'),
    path('veloce/content/buy_sell/', views.listings.buy_sell, name='buy_sell'),
    path('veloce/content/equipment_finance/', views.listings.equipment_finance, name='equipment_finance'),
    path('veloce/content/bill_finance/', views.listings.bill_finance, name='bill_finance'),
    path('veloce/content/testimonials/', views.listings.testimonials, name='testimonials'),
    path('veloce/content/contactus/', views.listings.contactus, name='contactus'),
    path('veloce/content/terms_of_use/', views.listings.terms_of_use, name='terms_of_use'),
    path('veloce/content/privacy_security_policy/', views.listings.privacy_security_policy, name='privacy_security_policy'),
    path('veloce/content/grievance_redressal/', views.listings.grievance_redressal, name='grievance_redressal'),
    path('veloce/content/fair_practices_code/', views.listings.fair_practices_code, name='fair_practices_code'),
    path('veloce/content/rbi_guidelines_disclaimer/', views.listings.rbi_guidelines_disclaimer, name='rbi_guidelines_disclaimer'),
    path('veloce/content/support/', views.listings.support, name='support'),
    path('veloce/content/fb_text/', views.listings.fb_text, name='fb_text'),
    path('compare-products/', views.listings.compare_product, name='compare_product'),
    path('compare_products_details', views.listings.compare_products_details, name='compare_products_details'),
    path('delete-image-by-id/', views.listings.delete_image_by_id, name='delete_image_by_id'),
    path('delete-bill-upload-by-id/', views.listings.delete_bill_upload_by_id, name='delete_bill_upload_by_id'),
    path('get_bill_details', views.listings.get_bill_details, name='get_bill_details'),
    path('dashboard/edit-bill/<int:id>/', views.listings.edit_uploaded_bill, name='edit_uploaded_bill'),
    path('product-ratings/<int:id>/', views.home.get_all_rating_by_id, name='product-rating'),
    path('bill-finance-details/<int:id>/', views.listings.bill_finance_details, name='bill-finance-details'),


# dealer profiles
    path('dealer-list/', views.home.dealer_list, name='dealer_list'),
    path('ajax-approve-dealer/', views.home.ajax_approve_dealer, name='ajax_approve_dealer'),
    path('dealer-list/view-dealer-selected-by-institution/', views.home.view_dealer_selected_by_institution, name='view_dealer_selected_by_institution'),
    path('remove-dealer-pending/', views.home.remove_dealer_pending, name='remove_dealer_pending'),
    path('ajax-approve-company-selected-product/',views.home.approve_company_selected_product,name='approve_company_selected_product'),
    path('approveby-institution/', views.home.approveby_institution, name='approveby_institution'),
    path('cross-delete-record-reason/',views.home.cross_delete_record_reason,name="cross_delete_record_reason"),

    #created by ravi
    path('approveby-dealer/', views.home.approveby_dealer, name='approveby_dealer'),
    path('ajax-approve-company/', views.home.ajax_approve_company, name='ajax_approve_company'),
    path('remove-company-pending/', views.home.remove_company_pending, name='remove_company_pending'),
    path('get-product-by-id/', views.home.get_product_by_id, name='get_product_by_id'),
    path('cross-approve-by-dealer/', views.home.cross_approve_by_dealer, name='cross_approve_by_dealer'),
    path('select-product-by-dealer-sell/', views.home.select_product_by_dealer_sell, name='select_product_by_dealer_sell'),
    path('dealer-cross-delete-record-reason/',views.home.dealer_cross_delete_record_reason,name="dealer_cross_delete_record_reason"),



]
