"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jdphf(nox@rri^fy4t-cxlls5z*eq67+x!%!q-+i#k5y51v06z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.0.20', '219.91.133.101']
# ALLOWED_HOSTS = ['veloce.market', 'localhost', '127.0.0.1', '168.138.114.166', 'www.veloce.market', '172.16.100.255',]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'veloce.apps.VeloceConfig',
    'widget_tweaks',
    'oauth2_provider',
    'social_django',
    'corsheaders',
    'django_social_share',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'veloce.views.utils.MenuInjectionMiddleware'
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'veloce/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'marketplace_dev',
        'USER': 'postgres',
        'PASSWORD': 'VeloceInnov002',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = [
    'veloce.oauth.VeloceOAuth2',
    'django.contrib.auth.backends.ModelBackend'
]

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_VAUTH_KEY = 'hG5XBhRRLwz4SVxQ9KlG5OBWF390XvWyjkzA1v4k'
SOCIAL_AUTH_VAUTH_SECRET = '2cY8YoqIvv5QOaMCauGnQVNCnKtV7COHwr8tanLzuefD4Pdyrsx1CVKi17sXAeNdFSZwCWJFTX4PxhyZb2AkC5BoYWhdcCcfjuvVjfZNhRXFLFpYpmJTzemrblRm8OSp'
OAUTH_URL = 'http://192.168.0.20:7004'
# OAUTH_URL = 'http://localhost:8085'
#OAUTH_URL = 'https://veloceinnovations.tech'

#SOCIAL_AUTH_VAUTH_KEY = 'zb8JqzU3Xjaj9B35T0a97He8nV3cwcOf6q5Lqbfx'
#SOCIAL_AUTH_VAUTH_SECRET = 'iY1JTZByTSJVCRwIY3t9xhTywstwMkRH44bR6cPGlkeXe8RGqgfUvFtN9ZDJ1RbzTeJ8wqsteBJXH9i5YQZsmnXFHxcHRM6AJyHsi98GgLGSoG4tOaCUUmkFt5ljcNm7'
#OAUTH_URL = 'https://veloceinnovations.herokuapp.com'

# fintech redirect url
# FINTECH_URL = 'http://localhost:8586'
FINTECH_URL = 'http://192.168.0.20:7003'
# OAUTH_URL ='/login/vauth/'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

CORS_ORIGIN_ALLOW_ALL = True
SOCIAL_AUTH_SESSION_EXPIRATION = False

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '')


# secure proxy SSL header and secure cookies
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

# session expire at browser close
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# wsgi scheme
# os.environ['wsgi.url_scheme'] = 'https'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

